### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by molotow11** [gaiterjones/Magento2_MessageManager#1]
Hello,

I have Magento 2.4.2 with Composer 2

composer require gaiterjones/Magento2_MessageManager

 [InvalidArgumentException]
  Could not find a matching version of package gaiterjones/Magento2_MessageManager. Check the package spelling, your version constraint and that the package is available in a stability w
  hich matches your minimum-stability (stable).

Please, could you suggest what to do here?

**Comment by gaiterjones** [comment]
I haven't developed the install for composer, I recommend you install it manually by downloading the git package and copying to `app/code/Gaiterjones/MessageManager` then run `bin/magento s:up`
